// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: controller.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType represents the type of node event
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED           EventType = 0
	EventType_EVENT_TYPE_NODE_ONLINE           EventType = 1
	EventType_EVENT_TYPE_NODE_OFFLINE          EventType = 2
	EventType_EVENT_TYPE_NODE_STATUS_UPDATE    EventType = 3
	EventType_EVENT_TYPE_SERVER_CREATED        EventType = 4
	EventType_EVENT_TYPE_SERVER_STARTED        EventType = 5
	EventType_EVENT_TYPE_SERVER_STOPPED        EventType = 6
	EventType_EVENT_TYPE_SERVER_ERROR          EventType = 7
	EventType_EVENT_TYPE_METRICS_UPDATE        EventType = 8
	EventType_EVENT_TYPE_LOG                   EventType = 9
	EventType_EVENT_TYPE_HEARTBEAT             EventType = 10
	EventType_EVENT_TYPE_FILE_OPERATION_RESULT EventType = 11
	EventType_EVENT_TYPE_COMMAND_RESULT        EventType = 12
)

func (e EventType) String() string {
	switch e {
	case EventType_EVENT_TYPE_NODE_ONLINE:
		return "NODE_ONLINE"
	case EventType_EVENT_TYPE_NODE_OFFLINE:
		return "NODE_OFFLINE"
	case EventType_EVENT_TYPE_NODE_STATUS_UPDATE:
		return "NODE_STATUS_UPDATE"
	case EventType_EVENT_TYPE_SERVER_CREATED:
		return "SERVER_CREATED"
	case EventType_EVENT_TYPE_SERVER_STARTED:
		return "SERVER_STARTED"
	case EventType_EVENT_TYPE_SERVER_STOPPED:
		return "SERVER_STOPPED"
	case EventType_EVENT_TYPE_SERVER_ERROR:
		return "SERVER_ERROR"
	case EventType_EVENT_TYPE_METRICS_UPDATE:
		return "METRICS_UPDATE"
	case EventType_EVENT_TYPE_LOG:
		return "LOG"
	case EventType_EVENT_TYPE_HEARTBEAT:
		return "HEARTBEAT"
	case EventType_EVENT_TYPE_FILE_OPERATION_RESULT:
		return "FILE_OPERATION_RESULT"
	case EventType_EVENT_TYPE_COMMAND_RESULT:
		return "COMMAND_RESULT"
	default:
		return "UNSPECIFIED"
	}
}

// CommandType represents the type of controller command
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED     CommandType = 0
	CommandType_COMMAND_TYPE_CREATE_SERVER   CommandType = 1
	CommandType_COMMAND_TYPE_UPDATE_SERVER   CommandType = 2
	CommandType_COMMAND_TYPE_DELETE_SERVER   CommandType = 3
	CommandType_COMMAND_TYPE_START_SERVER    CommandType = 4
	CommandType_COMMAND_TYPE_STOP_SERVER     CommandType = 5
	CommandType_COMMAND_TYPE_RESTART_SERVER  CommandType = 6
	CommandType_COMMAND_TYPE_EXECUTE_COMMAND CommandType = 7
	CommandType_COMMAND_TYPE_FILE_LIST       CommandType = 10
	CommandType_COMMAND_TYPE_FILE_CREATE     CommandType = 11
	CommandType_COMMAND_TYPE_FILE_DELETE     CommandType = 12
	CommandType_COMMAND_TYPE_FILE_RENAME     CommandType = 13
	CommandType_COMMAND_TYPE_FILE_MOVE       CommandType = 14
	CommandType_COMMAND_TYPE_FILE_COPY       CommandType = 15
	CommandType_COMMAND_TYPE_FILE_WRITE      CommandType = 16
	CommandType_COMMAND_TYPE_FILE_READ       CommandType = 17
	CommandType_COMMAND_TYPE_FILE_ZIP        CommandType = 18
	CommandType_COMMAND_TYPE_FILE_UNZIP      CommandType = 19
	CommandType_COMMAND_TYPE_FILE_EXISTS     CommandType = 20
	CommandType_COMMAND_TYPE_FILE_MKDIR      CommandType = 21
)

func (c CommandType) String() string {
	switch c {
	case CommandType_COMMAND_TYPE_CREATE_SERVER:
		return "CREATE_SERVER"
	case CommandType_COMMAND_TYPE_UPDATE_SERVER:
		return "UPDATE_SERVER"
	case CommandType_COMMAND_TYPE_DELETE_SERVER:
		return "DELETE_SERVER"
	case CommandType_COMMAND_TYPE_START_SERVER:
		return "START_SERVER"
	case CommandType_COMMAND_TYPE_STOP_SERVER:
		return "STOP_SERVER"
	case CommandType_COMMAND_TYPE_RESTART_SERVER:
		return "RESTART_SERVER"
	case CommandType_COMMAND_TYPE_EXECUTE_COMMAND:
		return "EXECUTE_COMMAND"
	case CommandType_COMMAND_TYPE_FILE_LIST:
		return "FILE_LIST"
	case CommandType_COMMAND_TYPE_FILE_CREATE:
		return "FILE_CREATE"
	case CommandType_COMMAND_TYPE_FILE_DELETE:
		return "FILE_DELETE"
	case CommandType_COMMAND_TYPE_FILE_RENAME:
		return "FILE_RENAME"
	case CommandType_COMMAND_TYPE_FILE_MOVE:
		return "FILE_MOVE"
	case CommandType_COMMAND_TYPE_FILE_COPY:
		return "FILE_COPY"
	case CommandType_COMMAND_TYPE_FILE_WRITE:
		return "FILE_WRITE"
	case CommandType_COMMAND_TYPE_FILE_READ:
		return "FILE_READ"
	case CommandType_COMMAND_TYPE_FILE_ZIP:
		return "FILE_ZIP"
	case CommandType_COMMAND_TYPE_FILE_UNZIP:
		return "FILE_UNZIP"
	case CommandType_COMMAND_TYPE_FILE_EXISTS:
		return "FILE_EXISTS"
	case CommandType_COMMAND_TYPE_FILE_MKDIR:
		return "FILE_MKDIR"
	default:
		return "UNSPECIFIED"
	}
}

// NodeHealth represents the health status of a node
type NodeHealth int32

const (
	NodeHealth_NODE_HEALTH_UNSPECIFIED NodeHealth = 0
	NodeHealth_NODE_HEALTH_HEALTHY     NodeHealth = 1
	NodeHealth_NODE_HEALTH_DEGRADED    NodeHealth = 2
	NodeHealth_NODE_HEALTH_UNHEALTHY   NodeHealth = 3
	NodeHealth_NODE_HEALTH_CRITICAL    NodeHealth = 4
)

func (n NodeHealth) String() string {
	switch n {
	case NodeHealth_NODE_HEALTH_HEALTHY:
		return "HEALTHY"
	case NodeHealth_NODE_HEALTH_DEGRADED:
		return "DEGRADED"
	case NodeHealth_NODE_HEALTH_UNHEALTHY:
		return "UNHEALTHY"
	case NodeHealth_NODE_HEALTH_CRITICAL:
		return "CRITICAL"
	default:
		return "UNSPECIFIED"
	}
}

// ServerState represents the state of a game server
type ServerState int32

const (
	ServerState_SERVER_STATE_UNSPECIFIED  ServerState = 0
	ServerState_SERVER_STATE_INSTALLING   ServerState = 1
	ServerState_SERVER_STATE_CONFIGURING  ServerState = 2
	ServerState_SERVER_STATE_STARTING     ServerState = 3
	ServerState_SERVER_STATE_RUNNING      ServerState = 4
	ServerState_SERVER_STATE_STOPPING     ServerState = 5
	ServerState_SERVER_STATE_STOPPED      ServerState = 6
	ServerState_SERVER_STATE_ERROR        ServerState = 7
	ServerState_SERVER_STATE_BACKING_UP   ServerState = 8
	ServerState_SERVER_STATE_UPDATING     ServerState = 9
)

func (s ServerState) String() string {
	switch s {
	case ServerState_SERVER_STATE_INSTALLING:
		return "INSTALLING"
	case ServerState_SERVER_STATE_CONFIGURING:
		return "CONFIGURING"
	case ServerState_SERVER_STATE_STARTING:
		return "STARTING"
	case ServerState_SERVER_STATE_RUNNING:
		return "RUNNING"
	case ServerState_SERVER_STATE_STOPPING:
		return "STOPPING"
	case ServerState_SERVER_STATE_STOPPED:
		return "STOPPED"
	case ServerState_SERVER_STATE_ERROR:
		return "ERROR"
	case ServerState_SERVER_STATE_BACKING_UP:
		return "BACKING_UP"
	case ServerState_SERVER_STATE_UPDATING:
		return "UPDATING"
	default:
		return "UNSPECIFIED"
	}
}

// LogLevel represents the severity of a log entry
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARNING     LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
	LogLevel_LOG_LEVEL_FATAL       LogLevel = 5
)

func (l LogLevel) String() string {
	switch l {
	case LogLevel_LOG_LEVEL_DEBUG:
		return "DEBUG"
	case LogLevel_LOG_LEVEL_INFO:
		return "INFO"
	case LogLevel_LOG_LEVEL_WARNING:
		return "WARNING"
	case LogLevel_LOG_LEVEL_ERROR:
		return "ERROR"
	case LogLevel_LOG_LEVEL_FATAL:
		return "FATAL"
	default:
		return "UNSPECIFIED"
	}
}

// Message types

// RegisterNodeRequest represents a node registration request
type RegisterNodeRequest struct {
	NodeId         string         `json:"nodeId"`
	Hostname       string         `json:"hostname"`
	IpAddress      string         `json:"ipAddress"`
	Resources      *NodeResources `json:"resources"`
	SupportedGames []string       `json:"supportedGames"`
	OsVersion      string         `json:"osVersion"`
	AgentVersion   string         `json:"agentVersion"`
}

// RegisterNodeResponse represents the response from node registration
type RegisterNodeResponse struct {
	ControllerId             string             `json:"controllerId"`
	HeartbeatIntervalSeconds int64              `json:"heartbeatIntervalSeconds"`
	PendingServers           []*ServerAssignment `json:"pendingServers"`
	ControllerConfig         *ControllerConfig  `json:"controllerConfig"`
}

// NodeResources represents resources available on a node
type NodeResources struct {
	TotalCpuCores      int32  `json:"totalCpuCores"`
	TotalMemoryMb      int64  `json:"totalMemoryMb"`
	TotalStorageMb     int64  `json:"totalStorageMb"`
	AvailableCpuCores  int32  `json:"availableCpuCores"`
	AvailableMemoryMb  int64  `json:"availableMemoryMb"`
	AvailableStorageMb int64  `json:"availableStorageMb"`
	CpuModel           string `json:"cpuModel"`
	NetworkInterface   string `json:"networkInterface"`
	NetworkSpeedMbps   int64  `json:"networkSpeedMbps"`
}

// NodeEvent represents an event from a node
type NodeEvent struct {
	NodeId        string           `json:"nodeId"`
	Type          EventType        `json:"type"`
	Timestamp     int64            `json:"timestamp"`
	Status        *NodeStatus      `json:"status,omitempty"`
	ServerStatus  *ServerStatus    `json:"serverStatus,omitempty"`
	Metrics       *MetricsSnapshot `json:"metrics,omitempty"`
	Log           *LogEntry        `json:"log,omitempty"`
	Error         *ErrorInfo       `json:"error,omitempty"`
	FileResult    *FileOpResult    `json:"fileResult,omitempty"`
	CommandResult *CommandResult   `json:"commandResult,omitempty"`
}

// ControllerCommand represents a command from the controller
type ControllerCommand struct {
	CommandId    string              `json:"commandId"`
	ServerId     string              `json:"serverId"`
	Type         CommandType         `json:"type"`
	Timestamp    int64               `json:"timestamp"`
	CreateServer *CreateServerCmd    `json:"createServer,omitempty"`
	UpdateServer *UpdateServerCmd    `json:"updateServer,omitempty"`
	DeleteServer *DeleteServerCmd    `json:"deleteServer,omitempty"`
	StartServer  *StartServerCmd     `json:"startServer,omitempty"`
	StopServer   *StopServerCmd      `json:"stopServer,omitempty"`
	FileList     *FileListCmd        `json:"fileList,omitempty"`
	FileCreate   *FileCreateCmd      `json:"fileCreate,omitempty"`
	FileDelete   *FileDeleteCmd      `json:"fileDelete,omitempty"`
	FileRename   *FileRenameCmd      `json:"fileRename,omitempty"`
	FileMove     *FileMoveCmd        `json:"fileMove,omitempty"`
	FileCopy     *FileCopyCmd        `json:"fileCopy,omitempty"`
	FileWrite    *FileWriteCmd       `json:"fileWrite,omitempty"`
	FileRead     *FileReadCmd        `json:"fileRead,omitempty"`
	FileZip      *FileZipCmd         `json:"fileZip,omitempty"`
	FileUnzip    *FileUnzipCmd       `json:"fileUnzip,omitempty"`
	FileExists   *FileExistsCmd      `json:"fileExists,omitempty"`
	FileMkdir    *FileMkdirCmd       `json:"fileMkdir,omitempty"`
}

// Server Commands

// CreateServerCmd contains parameters for creating a server
type CreateServerCmd struct {
	ServerId     string               `json:"serverId"`
	GameType     string               `json:"gameType"`
	Config       *ServerConfig        `json:"config"`
	Requirements *ResourceRequirements `json:"requirements"`
}

// UpdateServerCmd contains parameters for updating a server
type UpdateServerCmd struct {
	ServerId        string       `json:"serverId"`
	Config          *ServerConfig `json:"config"`
	RestartRequired bool         `json:"restartRequired"`
}

// DeleteServerCmd contains parameters for deleting a server
type DeleteServerCmd struct {
	ServerId           string `json:"serverId"`
	BackupBeforeDelete bool   `json:"backupBeforeDelete"`
}

// StartServerCmd contains parameters for starting a server
type StartServerCmd struct {
	ServerId   string            `json:"serverId"`
	Environment map[string]string `json:"environment"`
}

// StopServerCmd contains parameters for stopping a server
type StopServerCmd struct {
	ServerId            string `json:"serverId"`
	GracePeriodSeconds  int32  `json:"gracePeriodSeconds"`
	Reason              string `json:"reason"`
}

// File Commands

// FileListCmd contains parameters for listing files
type FileListCmd struct {
	Path      string `json:"path"`
	Recursive bool   `json:"recursive"`
}

// FileCreateCmd contains parameters for creating a file
type FileCreateCmd struct {
	Path        string `json:"path"`
	IsDirectory bool   `json:"isDirectory"`
}

// FileDeleteCmd contains parameters for deleting a file
type FileDeleteCmd struct {
	Path      string `json:"path"`
	Recursive bool   `json:"recursive"`
}

// FileRenameCmd contains parameters for renaming a file
type FileRenameCmd struct {
	OldPath string `json:"oldPath"`
	NewPath string `json:"newPath"`
}

// FileMoveCmd contains parameters for moving a file
type FileMoveCmd struct {
	SourcePath string `json:"sourcePath"`
	DestPath   string `json:"destPath"`
}

// FileCopyCmd contains parameters for copying a file
type FileCopyCmd struct {
	SourcePath string `json:"sourcePath"`
	DestPath   string `json:"destPath"`
	Recursive  bool   `json:"recursive"`
}

// FileWriteCmd contains parameters for writing a file
type FileWriteCmd struct {
	Path    string `json:"path"`
	Content []byte `json:"content"`
	Append  bool   `json:"append"`
}

// FileReadCmd contains parameters for reading a file
type FileReadCmd struct {
	Path   string `json:"path"`
	Offset int64  `json:"offset"`
	Length int64  `json:"length"`
}

// FileZipCmd contains parameters for zipping files
type FileZipCmd struct {
	SourcePath string `json:"sourcePath"`
	DestPath   string `json:"destPath"`
	Recursive  bool   `json:"recursive"`
}

// FileUnzipCmd contains parameters for unzipping files
type FileUnzipCmd struct {
	SourcePath string `json:"sourcePath"`
	DestPath   string `json:"destPath"`
}

// FileExistsCmd contains parameters for checking file existence
type FileExistsCmd struct {
	Path string `json:"path"`
}

// FileMkdirCmd contains parameters for creating a directory
type FileMkdirCmd struct {
	Path    string `json:"path"`
	Parents bool   `json:"parents"`
}

// Data types

// ServerConfig contains configuration for a game server
type ServerConfig struct {
	Name       string            `json:"name"`
	Version    string            `json:"version"`
	Settings   map[string]string `json:"settings"`
	Mods       []string          `json:"mods"`
	MaxPlayers int32             `json:"maxPlayers"`
	WorldName  string            `json:"worldName"`
	OnlineMode bool              `json:"onlineMode"`
	QueryType  string            `json:"queryType"`
}

// ResourceRequirements represents resource requirements for a server
type ResourceRequirements struct {
	MinCpuCores         int32 `json:"minCpuCores"`
	MinMemoryMb         int64 `json:"minMemoryMb"`
	MinStorageMb        int64 `json:"minStorageMb"`
	MaxCpuCores         int32 `json:"maxCpuCores"`
	MaxMemoryMb         int64 `json:"maxMemoryMb"`
	MaxPlayers          int32 `json:"maxPlayers"`
	NetworkBandwidthMbps int32 `json:"networkBandwidthMbps"`
}

// NodeStatus represents the status of a node
type NodeStatus struct {
	NodeId        string         `json:"nodeId"`
	Health        NodeHealth     `json:"health"`
	Resources     *NodeResources `json:"resources"`
	UptimeSeconds int64          `json:"uptimeSeconds"`
	ActiveServers int32          `json:"activeServers"`
	QueuedTasks   int32          `json:"queuedTasks"`
	Timestamp     int64          `json:"timestamp"`
}

// ServerStatus represents the status of a game server
type ServerStatus struct {
	ServerId       string   `json:"serverId"`
	State          ServerState `json:"state"`
	PlayerCount    int32    `json:"playerCount"`
	OnlinePlayers  []string `json:"onlinePlayers"`
	UptimeSeconds  int64    `json:"uptimeSeconds"`
	CpuUsagePercent int32   `json:"cpuUsagePercent"`
	MemoryUsageMb  int64    `json:"memoryUsageMb"`
	Tps            int32    `json:"tps"`
	Mspt           int32    `json:"mspt"`
	Timestamp      int64    `json:"timestamp"`
}

// MetricsSnapshot represents a snapshot of node metrics
type MetricsSnapshot struct {
	NodeId              string  `json:"nodeId"`
	CpuUsagePercent     float32 `json:"cpuUsagePercent"`
	MemoryUsagePercent  float32 `json:"memoryUsagePercent"`
	StorageUsagePercent float32 `json:"storageUsagePercent"`
	NetworkBytesIn      int64   `json:"networkBytesIn"`
	NetworkBytesOut     int64   `json:"networkBytesOut"`
	ActiveConnections   int32   `json:"activeConnections"`
	Timestamp           int64   `json:"timestamp"`
}

// LogEntry represents a log entry
type LogEntry struct {
	ServerId   string   `json:"serverId"`
	Level      LogLevel `json:"level"`
	Message    string   `json:"message"`
	Source     string   `json:"source"`
	Timestamp  int64    `json:"timestamp"`
	LineNumber int32    `json:"lineNumber"`
}

// ErrorInfo represents error information
type ErrorInfo struct {
	Code       string `json:"code"`
	Message    string `json:"message"`
	Details    string `json:"details"`
	StackTrace string `json:"stackTrace"`
}

// FileInfo represents information about a file
type FileInfo struct {
	Name         string `json:"name"`
	Path         string `json:"path"`
	IsDirectory  bool   `json:"isDirectory"`
	Size         int64  `json:"size"`
	ModifiedTime int64  `json:"modifiedTime"`
	CreatedTime  int64  `json:"createdTime"`
	Permissions  string `json:"permissions"`
}

// FileOpResult represents the result of a file operation
type FileOpResult struct {
	CommandId    string            `json:"commandId"`
	Success      bool              `json:"success"`
	Error        string            `json:"error"`
	ListResult   *FileListResult   `json:"listResult,omitempty"`
	ReadResult   *FileReadResult   `json:"readResult,omitempty"`
	ExistsResult *FileExistsResult `json:"existsResult,omitempty"`
}

// FileListResult contains the result of a file list operation
type FileListResult struct {
	Files       []*FileInfo `json:"files"`
	CurrentPath string      `json:"currentPath"`
}

// FileReadResult contains the result of a file read operation
type FileReadResult struct {
	Content   []byte `json:"content"`
	TotalSize int64  `json:"totalSize"`
}

// FileExistsResult contains the result of a file exists check
type FileExistsResult struct {
	Exists      bool `json:"exists"`
	IsDirectory bool `json:"isDirectory"`
}

// CommandResult represents the result of a command
type CommandResult struct {
	CommandId string `json:"commandId"`
	Success   bool   `json:"success"`
	Message   string `json:"message"`
}

// ControllerConfig represents controller configuration
type ControllerConfig struct {
	ControllerAddress     string `json:"controllerAddress"`
	GrpcPort              int32  `json:"grpcPort"`
	RestPort              int32  `json:"restPort"`
	MetricsIntervalSeconds int64 `json:"metricsIntervalSeconds"`
	AutoUpdateEnabled     bool   `json:"autoUpdateEnabled"`
}

// ServerAssignment represents a server assignment for a node
type ServerAssignment struct {
	ServerId string       `json:"serverId"`
	GameType string       `json:"gameType"`
	Config   *ServerConfig `json:"config"`
}

// ServerInfo represents information about a server
type ServerInfo struct {
	ServerId    string `json:"serverId"`
	NodeId      string `json:"nodeId"`
	Port        int32  `json:"port"`
	RconAddress string `json:"rconAddress"`
	RconPort    int32  `json:"rconPort"`
}

// Request/Response types for File Service

// FileListRequest represents a request to list files
type FileListRequest struct {
	NodeId    string `json:"nodeId"`
	Path      string `json:"path"`
	Recursive bool   `json:"recursive"`
}

// FileListResponse represents the response from listing files
type FileListResponse struct {
	Success     bool        `json:"success"`
	Error       string      `json:"error"`
	Files       []*FileInfo `json:"files"`
	CurrentPath string      `json:"currentPath"`
}

// FileCreateRequest represents a request to create a file
type FileCreateRequest struct {
	NodeId      string `json:"nodeId"`
	Path        string `json:"path"`
	IsDirectory bool   `json:"isDirectory"`
}

// FileDeleteRequest represents a request to delete a file
type FileDeleteRequest struct {
	NodeId    string `json:"nodeId"`
	Path      string `json:"path"`
	Recursive bool   `json:"recursive"`
}

// FileRenameRequest represents a request to rename a file
type FileRenameRequest struct {
	NodeId  string `json:"nodeId"`
	OldPath string `json:"oldPath"`
	NewPath string `json:"newPath"`
}

// FileMoveRequest represents a request to move a file
type FileMoveRequest struct {
	NodeId     string `json:"nodeId"`
	SourcePath string `json:"sourcePath"`
	DestPath   string `json:"destPath"`
}

// FileCopyRequest represents a request to copy a file
type FileCopyRequest struct {
	NodeId     string `json:"nodeId"`
	SourcePath string `json:"sourcePath"`
	DestPath   string `json:"destPath"`
	Recursive  bool   `json:"recursive"`
}

// FileReadRequest represents a request to read a file
type FileReadRequest struct {
	NodeId string `json:"nodeId"`
	Path   string `json:"path"`
	Offset int64  `json:"offset"`
	Length int64  `json:"length"`
}

// FileReadResponse represents the response from reading a file
type FileReadResponse struct {
	Success   bool   `json:"success"`
	Error     string `json:"error"`
	Content   []byte `json:"content"`
	TotalSize int64  `json:"totalSize"`
}

// FileWriteRequest represents a request to write a file
type FileWriteRequest struct {
	NodeId  string `json:"nodeId"`
	Path    string `json:"path"`
	Content []byte `json:"content"`
	Append  bool   `json:"append"`
}

// FileExistsRequest represents a request to check if a file exists
type FileExistsRequest struct {
	NodeId string `json:"nodeId"`
	Path   string `json:"path"`
}

// FileExistsResponse represents the response from checking if a file exists
type FileExistsResponse struct {
	Success    bool   `json:"success"`
	Error      string `json:"error"`
	Exists     bool   `json:"exists"`
	IsDirectory bool   `json:"isDirectory"`
}

// FileMkdirRequest represents a request to create a directory
type FileMkdirRequest struct {
	NodeId  string `json:"nodeId"`
	Path    string `json:"path"`
	Parents bool   `json:"parents"`
}

// FileZipRequest represents a request to zip files
type FileZipRequest struct {
	NodeId     string `json:"nodeId"`
	SourcePath string `json:"sourcePath"`
	DestPath   string `json:"destPath"`
	Recursive  bool   `json:"recursive"`
}

// FileUnzipRequest represents a request to unzip files
type FileUnzipRequest struct {
	NodeId     string `json:"nodeId"`
	SourcePath string `json:"sourcePath"`
	DestPath   string `json:"destPath"`
}

// FileOperationResponse represents the response from a file operation
type FileOperationResponse struct {
	Success bool   `json:"success"`
	Error   string `json:"error"`
	Message string `json:"message"`
}

// Request/Response types for Server Service

// CreateServerRequest represents a request to create a server
type CreateServerRequest struct {
	NodeId       string               `json:"nodeId"`
	GameType     string               `json:"gameType"`
	Config       *ServerConfig        `json:"config"`
	Requirements *ResourceRequirements `json:"requirements"`
}

// CreateServerResponse represents the response from creating a server
type CreateServerResponse struct {
	Success  bool        `json:"success"`
	ServerId string      `json:"serverId"`
	Message  string      `json:"message"`
	Info     *ServerInfo `json:"info"`
}

// UpdateServerRequest represents a request to update a server
type UpdateServerRequest struct {
	ServerId string       `json:"serverId"`
	Config   *ServerConfig `json:"config"`
	Restart  bool         `json:"restart"`
}

// UpdateServerResponse represents the response from updating a server
type UpdateServerResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// DeleteServerRequest represents a request to delete a server
type DeleteServerRequest struct {
	ServerId string `json:"serverId"`
	Backup   bool   `json:"backup"`
}

// DeleteServerResponse represents the response from deleting a server
type DeleteServerResponse struct {
	Success    bool   `json:"success"`
	Message    string `json:"message"`
	BackupPath string `json:"backupPath"`
}

// StartServerRequest represents a request to start a server
type StartServerRequest struct {
	ServerId string `json:"serverId"`
}

// StartServerResponse represents the response from starting a server
type StartServerResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// StopServerRequest represents a request to stop a server
type StopServerRequest struct {
	ServerId   string `json:"serverId"`
	GracePeriod int32  `json:"gracePeriod"`
}

// StopServerResponse represents the response from stopping a server
type StopServerResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// GetServerStatusRequest represents a request to get server status
type GetServerStatusRequest struct {
	ServerId string `json:"serverId"`
}

// GetServerStatusResponse represents the response from getting server status
type GetServerStatusResponse struct {
	Status *ServerStatus `json:"status"`
}

// StreamLogsRequest represents a request to stream logs
type StreamLogsRequest struct {
	ServerId  string   `json:"serverId"`
	MinLevel  LogLevel `json:"minLevel"`
	TailLines int32    `json:"tailLines"`
	Follow    bool     `json:"follow"`
}

// StreamMetricsRequest represents a request to stream metrics
type StreamMetricsRequest struct {
	NodeId     string `json:"nodeId"`
	IntervalMs int64  `json:"intervalMs"`
}

// NodeMetrics represents node metrics
type NodeMetrics struct {
	NodeId       string  `json:"nodeId"`
	CpuUsage     float32 `json:"cpuUsage"`
	MemoryUsage  float32 `json:"memoryUsage"`
	StorageUsage float32 `json:"storageUsage"`
	NetworkIn    int64   `json:"networkIn"`
	NetworkOut   int64   `json:"networkOut"`
	LoadAverage  int32   `json:"loadAverage"`
	Timestamp    int64   `json:"timestamp"`
}

// UpdateNodeStatusRequest represents a request to update node status
type UpdateNodeStatusRequest struct {
	NodeId string      `json:"nodeId"`
	Status *NodeStatus `json:"status"`
}

// UpdateNodeStatusResponse represents the response from updating node status
type UpdateNodeStatusResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// GetNodeConfigRequest represents a request to get node config
type GetNodeConfigRequest struct {
	NodeId string `json:"nodeId"`
}

// GetNodeConfigResponse represents the response from getting node config
type GetNodeConfigResponse struct {
	Config *ControllerConfig `json:"config"`
}

// File type references for protobuf implementation
var _ = protoreflect.Name("")
var _ = reflect.TypeFor[*FileInfo]()
var _ = sync.Mutex{}
